# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentry" do
  if OS.mac?
    postflight_steps do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "agentry"], chdir: "."
    end
  end

  version "0.32.0"

  on_macos do
    on_arm do
      sha256 "357d65c3f2abec79fe5e4be4d8e31de834f9c1cdf0d5d97bb93f11f288b2aacb"
      url "https://github.com/eitanpo/agentry/releases/download/v#{version}/agentry_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9a1181e52fdbdd349ecdad9e524c31abf4ceb7718f9b0a8d1a050ec038aa5fea"
      url "https://github.com/eitanpo/agentry/releases/download/v#{version}/agentry_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a6b022a6c2f036c131d6d5919dc30eddda053ea4380b4e4b5dbccfe6f18fd561"
      url "https://github.com/eitanpo/agentry/releases/download/v#{version}/agentry_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7d82ee9437b02d9fc00053f47ad2f14ee79dbd4417f9b80e54aae6a10e50e6d9"
      url "https://github.com/eitanpo/agentry/releases/download/v#{version}/agentry_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentry"
  desc "Render a Claude Code session log into a styled terminal view"
  homepage "https://github.com/eitanpo/agentry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentry"
  bash_completion "completions/agentry.bash"
  fish_completion "completions/agentry.fish"
  zsh_completion "completions/agentry.zsh"

  # No zap stanza required
end
