# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentry" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "6d64388756d6e23f1e4351deee8c793adaeb46f2038a8e2bfba633a02209e809"
      url "https://github.com/eitanpo/agentry/releases/download/v#{version}/agentry_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b0c2d542e8df6203de64855c90e57c2391239d12fd9ee941ec101f1745bab80"
      url "https://github.com/eitanpo/agentry/releases/download/v#{version}/agentry_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca7f0c0da0dbc1679ae28c89a910cf9821f2e908cc07fa9e2303ddb530310029"
      url "https://github.com/eitanpo/agentry/releases/download/v#{version}/agentry_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c0009654f23f0244619802a28786e8ae6f47bcba909b37f087f52073bf0d559"
      url "https://github.com/eitanpo/agentry/releases/download/v#{version}/agentry_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentry"
  desc "Render a Claude Code session log into a styled terminal view"
  homepage "https://github.com/eitanpo/agentry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentry"
  bash_completion "completions/agentry.bash"
  fish_completion "completions/agentry.fish"
  zsh_completion "completions/agentry.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentry"]
    end
  end

  # No zap stanza required

end
