# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentry" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "15f41422bd94c114a194baad1d8dd264c8a14bd6d3e1e27f8e7ae6cb6bee4a98"
      url "https://github.com/eitanpo/agentry/releases/download/v#{version}/agentry_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "be7426ad1d6d0766a0bb3f3f61d310b9190e50e75150091d7cfb9647e08793aa"
      url "https://github.com/eitanpo/agentry/releases/download/v#{version}/agentry_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d6296a91fc092ff18e8c06f469a5113d73a46d4de4ede80eeceecf60a8a4d46b"
      url "https://github.com/eitanpo/agentry/releases/download/v#{version}/agentry_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4417a248faff332fae38b0ee924b363bb1dcd19c2d93ee3baaf1acdf58bf3bce"
      url "https://github.com/eitanpo/agentry/releases/download/v#{version}/agentry_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentry"
  desc "Render a Claude Code session log into a styled terminal view"
  homepage "https://github.com/eitanpo/agentry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentry"]
    end
  end

  # No zap stanza required

end
