# This file was generated by GoReleaser. DO NOT EDIT.
cask "vault-search" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ef8ffbb12b341ec2bfed2d550b1696c25b8807e80a0d421ace22a793702889e8"
      url "https://github.com/eitanpo/vault-search/releases/download/v#{version}/vault-search_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "91d371bde3a9554c8c33cdb291766c7526f42ffe66b0a605e7f74c5a8d649c17"
      url "https://github.com/eitanpo/vault-search/releases/download/v#{version}/vault-search_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f250be1c01b117a2c5653e9f644bfa63911b45483c80acc88237095488983dea"
      url "https://github.com/eitanpo/vault-search/releases/download/v#{version}/vault-search_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "495395ea17aa3532fa0e3ec7653eee0e9f9d14761c902aec67176c6781a7ca84"
      url "https://github.com/eitanpo/vault-search/releases/download/v#{version}/vault-search_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vault-search"
  desc "Thin CLI over an obsidian-hybrid-search serve daemon for concurrent vault search"
  homepage "https://github.com/eitanpo/vault-search"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vault-search"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vault-search"]
    end
  end

  # No zap stanza required

end
