# This file was generated by GoReleaser. DO NOT EDIT.
cask "vault-search" do
  if OS.mac?
    postflight_steps do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "vault-search"], chdir: "."
    end
  end

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "29eeb41e5f021031af2fc3bb63bd8e3f926dbf2332575ca4f1a211f60ad1cf35"
      url "https://github.com/eitanpo/vault-search/releases/download/v#{version}/vault-search_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1b402efa5588018dca6a331733820b0b865004f6281a14b88ef9bf2619c2fa69"
      url "https://github.com/eitanpo/vault-search/releases/download/v#{version}/vault-search_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4e23845823ed3e04de879683fe3055b08712ef19b2d179993a062b778df866fa"
      url "https://github.com/eitanpo/vault-search/releases/download/v#{version}/vault-search_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f972c37418460d6b893f8fa59479a2825834edb42611f602c1dfc2ca6bbb79dd"
      url "https://github.com/eitanpo/vault-search/releases/download/v#{version}/vault-search_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vault-search"
  desc "Thin CLI over an obsidian-hybrid-search serve daemon for concurrent vault search"
  homepage "https://github.com/eitanpo/vault-search"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vault-search"

  # No zap stanza required
end
