# This file was generated by GoReleaser. DO NOT EDIT.
cask "vault-search" do
  if OS.mac?
    postflight_steps do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "vault-search"], chdir: "."
    end
  end

  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "e106dad743bbce34f1b082a798b72d94f0a97ad6895d524ebd23c85c339a89eb"
      url "https://github.com/eitanpo/vault-search/releases/download/v#{version}/vault-search_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2d2d4dcf199e05ef8e4ecfafa051c25be67cd31c6669566c6dd67c72de09021f"
      url "https://github.com/eitanpo/vault-search/releases/download/v#{version}/vault-search_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "48845ceebcd688c95b2139c27909b527d5f468aeef5355636f549aa76f5b5177"
      url "https://github.com/eitanpo/vault-search/releases/download/v#{version}/vault-search_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a47ca4e00775c899b0191a9e49d03b147a5928af81d918e37b47286788c23830"
      url "https://github.com/eitanpo/vault-search/releases/download/v#{version}/vault-search_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vault-search"
  desc "Thin CLI over an obsidian-hybrid-search serve daemon for concurrent vault search"
  homepage "https://github.com/eitanpo/vault-search"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vault-search"

  # No zap stanza required
end
